/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import DbClass.DBConnection;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prog imesh BSC
 */
public class AddCoach extends javax.swing.JFrame {

    /**
     * Creates new form AddCoach
     */
    public AddCoach() {
        initComponents();
        
    }
    PreparedStatement ps;
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        COMBOFrom2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        COMBOdestin = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        BTNadd = new javax.swing.JButton();
        DateAdd2 = new com.toedter.calendar.JDateChooser();
        TxtBusnum = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Back2BTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLEroute = new javax.swing.JTable();
        DATESearch = new com.toedter.calendar.JDateChooser();
        BTNclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(773, 440));
        jPanel1.setPreferredSize(new java.awt.Dimension(773, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Your Coach");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 770, 40));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Bus Number*");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Date");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 40, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("From");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 20));

        COMBOFrom2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        COMBOFrom2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "France", "Spain", "Germany", " " }));
        COMBOFrom2.setToolTipText("~ SELECT ~");
        jPanel2.add(COMBOFrom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 100, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Destination");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, 20));

        COMBOdestin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        COMBOdestin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "France", "Spain", "Germany", " " }));
        COMBOdestin.setToolTipText("~ SELECT ~");
        jPanel2.add(COMBOdestin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 100, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Recet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, 30));

        BTNadd.setBackground(new java.awt.Color(255, 153, 0));
        BTNadd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BTNadd.setForeground(new java.awt.Color(255, 255, 255));
        BTNadd.setText("Add");
        BTNadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNaddActionPerformed(evt);
            }
        });
        jPanel2.add(BTNadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 70, 30));
        jPanel2.add(DateAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, -1));

        TxtBusnum.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtBusnum.setToolTipText("");
        TxtBusnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBusnumActionPerformed(evt);
            }
        });
        TxtBusnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBusnumKeyTyped(evt);
            }
        });
        jPanel2.add(TxtBusnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 60, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 190, 250));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Show route list");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 390, 30));

        Back2BTN.setBackground(new java.awt.Color(0, 0, 255));
        Back2BTN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Back2BTN.setForeground(new java.awt.Color(255, 255, 255));
        Back2BTN.setText("Back");
        Back2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back2BTNActionPerformed(evt);
            }
        });
        jPanel1.add(Back2BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 70, 30));

        TABLEroute.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus Number", "Seats", "Status", " Name", "Telephone", "Date", "From ", "Destination"
            }
        ));
        TABLEroute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLErouteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLEroute);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 560, 250));

        DATESearch.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(DATESearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 160, 30));

        BTNclear.setBackground(new java.awt.Color(255, 153, 0));
        BTNclear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BTNclear.setForeground(new java.awt.Color(255, 255, 255));
        BTNclear.setText("clear");
        BTNclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNclearActionPerformed(evt);
            }
        });
        jPanel1.add(BTNclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resetadd();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Back2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back2BTNActionPerformed
        // TODO add your handling code here:
        CoachManmagementSystem log =new CoachManmagementSystem();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Back2BTNActionPerformed

    private void BTNaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNaddActionPerformed
        
        String busnum = TxtBusnum.getText();
        SimpleDateFormat datefornatter =new SimpleDateFormat("yyyy-MM-dd");
        String date = datefornatter.format(DateAdd2.getDate());
        int From = COMBOFrom2.getSelectedIndex();
        int Dest = COMBOdestin.getSelectedIndex();
        String from = COMBOFrom2.getSelectedItem().toString();
        String dest = COMBOdestin.getSelectedItem().toString();
        
        
        
        
        
        
        
        
        addcoach(From, Dest, busnum, date, from, dest);
        
        
    }//GEN-LAST:event_BTNaddActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateformatter = new SimpleDateFormat("yyyy-MM-dd");
        String sdate =dateformatter.format(DATESearch.getDate());
        showlist(sdate);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TxtBusnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBusnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBusnumActionPerformed

    private void TABLErouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLErouteMouseClicked
        // TODO add your handling code here:
      

    }//GEN-LAST:event_TABLErouteMouseClicked

    private void TxtBusnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBusnumKeyTyped
        // TODO add your handling code here:
        int blen = TxtBusnum.getText().length();

        if (blen >= 4) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TxtBusnumKeyTyped

    private void BTNclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNclearActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_BTNclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCoach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCoach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNadd;
    private javax.swing.JButton BTNclear;
    private javax.swing.JButton Back2BTN;
    private javax.swing.JComboBox<String> COMBOFrom2;
    private javax.swing.JComboBox<String> COMBOdestin;
    private com.toedter.calendar.JDateChooser DATESearch;
    private com.toedter.calendar.JDateChooser DateAdd2;
    private javax.swing.JTable TABLEroute;
    private javax.swing.JTextField TxtBusnum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void resetadd() {
        
        TxtBusnum.setText("");
        DateAdd2.setDate(null);
        COMBOFrom2.setSelectedIndex(0);
        COMBOdestin.setSelectedIndex(0);
                
    }

    private void addcoach(int From, int Dest, String busnum, String date, String from, String dest) {
         Connection dbcon = DBConnection.CreateDBConnection();
         
         PreparedStatement pt;
        
         if (dbcon != null) {
            if (From == Dest) {
                JOptionPane.showMessageDialog(rootPane, "Selection Errorr", "Save Error",
                        JOptionPane.ERROR_MESSAGE);
                AddCoach add = new AddCoach();
                add.setVisible(true);
                this.setVisible(false);

            }  else {

                for (int i = 1; i <= 24; i++) {

                    int seat = i;
                    String status = "Unbooked";

                    try {
                        pt = dbcon.prepareStatement("insert into busadd(BusNo,Fromthe,seat,Status,Destination,Date)values(?,?,?,?,?,?) ");
                        pt.setString(1, busnum);
                        pt.setString(2, from);
                        pt.setInt(3, seat);
                        pt.setString(4, status);
                        pt.setString(5, dest);
                        pt.setString(6, date);

                        pt.executeUpdate();

                    } catch (SQLException ex) {
                        ex.printStackTrace();

                    }

                }
                JOptionPane.showMessageDialog(rootPane, "Bus Added Successfully", "Save Success",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } else {

        }

    }

    private void showlist(String sdate) {
       
        
        Connection dbcon = DBConnection.CreateDBConnection();
        ResultSet rs;
        if(dbcon!=null){
            try {
                    ps = dbcon.prepareStatement("select busadd.BusNo, busadd.seat, busadd.Status, busadd.Date, busadd.Fromthe, busadd.Destination,  busbooking.cusname, busbooking.telephone from busadd left JOIN busbooking ON "
                            + "busadd.BusNo = busbooking.BusNo AND busadd.seat = busbooking.Seat AND busadd.Date = busbooking.Date AND"
                            + " busadd.Fromthe = busbooking.Fromthe AND busadd.Destination = busbooking.Destination where busadd.Date = ? ");

                    ps.setString(1, sdate);
                    rs = ps.executeQuery();

                    ResultSetMetaData rsmd = rs.getMetaData();

                    int c;

                    c = rsmd.getColumnCount();

                    DefaultTableModel d = (DefaultTableModel)TABLEroute.getModel();
                    d.setRowCount(0);

                    while (rs.next()) {

                        Vector v2 = new Vector();

                        for (int i = 1; i <= c; i++) {

                            v2.add(rs.getString("BusNo"));
                            v2.add(rs.getString("seat"));
                            v2.add(rs.getString("Status"));
                            v2.add(rs.getString("cusname"));
                            v2.add(rs.getString("telephone"));
                            v2.add(rs.getString("Date"));
                            v2.add(rs.getString("Fromthe"));
                            v2.add(rs.getString("Destination"));

                        }

                        d.addRow(v2);

                    }
                    

                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(rootPane, "Search resulst loading failed ", "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            
            
        }else{
            
        }
        
        
        
    }

    private void Clear() {
        
        DATESearch.setDate(null);
        COMBOFrom2.setSelectedIndex(0);
        COMBOdestin.setSelectedIndex(0);
        DefaultTableModel d = (DefaultTableModel)TABLEroute.getModel();
                d.setRowCount(0);
    }
         
       
  }

   

 /* try {
                int addedcount = dbcon.createStatement().executeUpdate("insert into addbus(seat, Status)values('"+seat+"','"+date+"') ");
                 
                if (addedcount > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Bus Added Successfully", "Save Success",
                            JOptionPane.INFORMATION_MESSAGE);
                     
                    AddCoach AC = new AddCoach();
                     AC.setVisible(true);
                     this.setVisible(false);
                     
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Invalid Information", "Save Error",
                            JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "ivalid information", "Save Error",
                        JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
                Connection dbcon = DBConnection.CreateDBConnection(); */