/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import DbClass.DBConnection;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Prog imesh BSC
 */
public class Bus_Employees_signup extends javax.swing.JFrame {

    /**
     * Creates new form Bus_Employees_Login
     */
    public Bus_Employees_signup() {
        initComponents();
        
        hidelable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtFirstname = new javax.swing.JTextField();
        TxtEmpConPW = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Back2BTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtEmpPW = new javax.swing.JPasswordField();
        TxtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Signup2BTN = new javax.swing.JButton();
        EResetBTN = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TxtSurename = new javax.swing.JTextField();
        lblWeak = new javax.swing.JLabel();
        lblMedium = new javax.swing.JLabel();
        lblStrong = new javax.swing.JLabel();
        lblTooShort = new javax.swing.JLabel();
        lblRetype = new javax.swing.JLabel();
        lblConfirmed = new javax.swing.JLabel();
        lblWrong = new javax.swing.JLabel();
        TxtTP = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(627, 436));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bus Employee Register Here");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 640, 40));

        TxtFirstname.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtFirstname.setToolTipText("");
        TxtFirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtFirstnameKeyTyped(evt);
            }
        });
        jPanel1.add(TxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 140, 20));

        TxtEmpConPW.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtEmpConPW.setToolTipText("");
        TxtEmpConPW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtEmpConPWKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtEmpConPWKeyTyped(evt);
            }
        });
        jPanel1.add(TxtEmpConPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 140, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Confirm Password*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 140, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Email Address*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 140, 20));

        Back2BTN.setBackground(new java.awt.Color(0, 0, 255));
        Back2BTN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Back2BTN.setForeground(new java.awt.Color(255, 255, 255));
        Back2BTN.setText("Back");
        Back2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back2BTNActionPerformed(evt);
            }
        });
        jPanel1.add(Back2BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 70, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Fisrt Name*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 140, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Password*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 140, 20));

        TxtEmpPW.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtEmpPW.setToolTipText("");
        TxtEmpPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEmpPWActionPerformed(evt);
            }
        });
        TxtEmpPW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtEmpPWKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtEmpPWKeyTyped(evt);
            }
        });
        jPanel1.add(TxtEmpPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 140, 20));

        TxtEmail.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtEmail.setToolTipText("");
        TxtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtEmailKeyTyped(evt);
            }
        });
        jPanel1.add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 140, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Telephone");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 140, 20));

        Signup2BTN.setBackground(new java.awt.Color(0, 0, 255));
        Signup2BTN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Signup2BTN.setForeground(new java.awt.Color(255, 255, 255));
        Signup2BTN.setText("Signup");
        Signup2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signup2BTNActionPerformed(evt);
            }
        });
        jPanel1.add(Signup2BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        EResetBTN.setBackground(new java.awt.Color(0, 0, 255));
        EResetBTN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        EResetBTN.setForeground(new java.awt.Color(255, 255, 255));
        EResetBTN.setText("Reset");
        EResetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EResetBTNActionPerformed(evt);
            }
        });
        jPanel1.add(EResetBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 70, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Surename*");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 140, 20));

        TxtSurename.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtSurename.setToolTipText("");
        TxtSurename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSurenameKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSurename, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 140, -1));

        lblWeak.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblWeak.setForeground(new java.awt.Color(204, 0, 0));
        lblWeak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWeak.setText("Weak");
        jPanel1.add(lblWeak, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 50, 20));

        lblMedium.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblMedium.setForeground(new java.awt.Color(0, 51, 204));
        lblMedium.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedium.setText("Medium");
        jPanel1.add(lblMedium, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 50, 20));

        lblStrong.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblStrong.setForeground(new java.awt.Color(51, 204, 0));
        lblStrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStrong.setText("Strong");
        jPanel1.add(lblStrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 50, 20));

        lblTooShort.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblTooShort.setForeground(new java.awt.Color(255, 102, 51));
        lblTooShort.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTooShort.setText("Too short");
        jPanel1.add(lblTooShort, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 50, 20));

        lblRetype.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblRetype.setForeground(new java.awt.Color(0, 102, 102));
        lblRetype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRetype.setText("Re- type your password");
        jPanel1.add(lblRetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 110, 20));

        lblConfirmed.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblConfirmed.setForeground(new java.awt.Color(0, 204, 0));
        lblConfirmed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirmed.setText("Password Confirmed");
        jPanel1.add(lblConfirmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 100, 20));

        lblWrong.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblWrong.setForeground(new java.awt.Color(255, 0, 0));
        lblWrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWrong.setText("Wrong Password");
        jPanel1.add(lblWrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 90, 20));

        try {
            TxtTP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtTP.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(TxtTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Back2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back2BTNActionPerformed
        // TODO add your handling code here:
        Register r=new Register();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Back2BTNActionPerformed

    private void Signup2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup2BTNActionPerformed
        // Read input values
        String firstname = TxtFirstname.getText();
        String suretname = TxtSurename.getText();
        String email = TxtEmail.getText();
        String password = TxtEmpPW.getText();
        String conpassword = TxtEmpConPW.getText();
        String telephone = TxtTP.getText();
        
        
        
        //checking pw match
        if(password.equals(conpassword)){
            savebusemp(firstname, suretname, email, password, telephone);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Passwords do not matched", "Save Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_Signup2BTNActionPerformed

    private void EResetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EResetBTNActionPerformed
        // TODO add your handling code here:
        ResetEsignup();
    }//GEN-LAST:event_EResetBTNActionPerformed

    private void TxtEmpPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEmpPWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEmpPWActionPerformed

    private void TxtEmpPWKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEmpPWKeyReleased
        // TODO add your handling code here:
        int Epasslength = TxtEmpPW.getText().length();
        
        if (Epasslength <= 3){
                lblTooShort.setVisible(true);
                lblWeak.setVisible(false);
                lblMedium.setVisible(false);
                lblStrong.setVisible(false);
            
        }else if (Epasslength >= 4 && Epasslength <=6){
                lblTooShort.setVisible(false);
                lblWeak.setVisible(true);
                lblMedium.setVisible(false);
                lblStrong.setVisible(false);

        }else if (Epasslength >= 7 && Epasslength <=8){
                lblTooShort.setVisible(false);
                lblWeak.setVisible(false);
                lblMedium.setVisible(true);
                lblStrong.setVisible(false);

        }else if (Epasslength >= 9 && Epasslength <=12){
                lblTooShort.setVisible(false);
                lblWeak.setVisible(false);
                lblMedium.setVisible(false);
                lblStrong.setVisible(true);
        
        
    }                             
                                        
    }//GEN-LAST:event_TxtEmpPWKeyReleased

    private void TxtEmpConPWKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEmpConPWKeyReleased
        // TODO add your handling code here:
       int Epasslength2 = TxtEmpConPW.getText().length();
     
       if (TxtEmpPW.getText().equals(TxtEmpConPW.getText())){
           
                lblRetype.setVisible(false);
                lblWrong.setVisible(false);
                lblConfirmed.setVisible(true);
       }else{
                lblRetype.setVisible(false);
                lblWrong.setVisible(true);
                lblConfirmed.setVisible(false);
       }
       
       if (Epasslength2 ==0){
           lblRetype.setVisible(true);
           lblWrong.setVisible(false);
           
       }else if (Epasslength2 >0){
           lblRetype.setVisible(false);
       } 
    }//GEN-LAST:event_TxtEmpConPWKeyReleased

    private void TxtEmpPWKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEmpPWKeyTyped
        // TODO add your handling code here:
        int Epasslength = TxtEmpPW.getText().length();
        
        if (Epasslength >= 12){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TxtEmpPWKeyTyped

    private void TxtEmpConPWKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEmpConPWKeyTyped
        // TODO add your handling code here:
        int Epasslength = TxtEmpPW.getText().length();
        
        if (Epasslength >= 12){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TxtEmpConPWKeyTyped

    private void TxtFirstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFirstnameKeyTyped
        // TODO add your handling code here:
        int Efn = TxtFirstname.getText().length();
        
        if (Efn >= 15){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TxtFirstnameKeyTyped

    private void TxtSurenameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSurenameKeyTyped
        // TODO add your handling code here:'
        int Esn = TxtSurename.getText().length();
        
        if (Esn >= 20){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TxtSurenameKeyTyped

    private void TxtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEmailKeyTyped
        // TODO add your handling code here:
        int Eemail = TxtEmail.getText().length();
        
        if (Eemail >= 50){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TxtEmailKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bus_Employees_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bus_Employees_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bus_Employees_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bus_Employees_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bus_Employees_signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back2BTN;
    private javax.swing.JButton EResetBTN;
    private javax.swing.JButton Signup2BTN;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JPasswordField TxtEmpConPW;
    private javax.swing.JPasswordField TxtEmpPW;
    private javax.swing.JTextField TxtFirstname;
    private javax.swing.JTextField TxtSurename;
    private javax.swing.JFormattedTextField TxtTP;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirmed;
    private javax.swing.JLabel lblMedium;
    private javax.swing.JLabel lblRetype;
    private javax.swing.JLabel lblStrong;
    private javax.swing.JLabel lblTooShort;
    private javax.swing.JLabel lblWeak;
    private javax.swing.JLabel lblWrong;
    // End of variables declaration//GEN-END:variables

    private void hidelable() {
        
         lblTooShort.setVisible(false);
         lblWeak.setVisible(false);
         lblMedium.setVisible(false);
         lblStrong.setVisible(false);
         lblRetype.setVisible(false);
         lblWrong.setVisible(false);
         lblConfirmed.setVisible(false);
        
    }

    private void ResetEsignup() {
        
         TxtFirstname.setText("");
         TxtSurename.setText("");
         TxtEmail.setText("");
         TxtEmpPW.setText("");
         TxtEmpConPW.setText("");
         TxtTP.setText("");
        
                 
        
         lblTooShort.setVisible(false);
         lblWeak.setVisible(false);
         lblMedium.setVisible(false);
         lblStrong.setVisible(false);
         lblRetype.setVisible(false);
         lblWrong.setVisible(false);
         lblConfirmed.setVisible(false);
    }

    private void savebusemp(String firstname, String suretname, String email, String password, String telephone) {
        
        //db connection
        Connection dbcon = DBConnection.CreateDBConnection();
        
        //query
        if(dbcon!=null){
            
            try {
                int addedcount = dbcon.createStatement().executeUpdate
                ("insert into busemployee(FistName, Surename, EmailAddress, Password, Telephone)values('"+firstname+"', '"+suretname+"', '"+email+"', '"+password+"', '"+telephone+"')");
                
                if (addedcount>0){
                    JOptionPane.showMessageDialog(rootPane, "Bus employee successfully registered", "Save Success", 
                        JOptionPane.INFORMATION_MESSAGE);
                    
                    CoachManmagementSystem signup = new CoachManmagementSystem();
                     signup.setVisible(true);
                     this.setVisible(false);
                     
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Bus employee registration failed", "Save Error", 
                        JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Bus employee registration failed", "Save Error",  
                        JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
            
           
        }else{
            JOptionPane.showMessageDialog(rootPane, "Bus employee registration failed", "Save Error", 
                        JOptionPane.ERROR_MESSAGE);
            
            
        }
         
        
        
        
    }
}
