package Frames;

import DbClass.DBConnection;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Prog imesh BSC
 */
public class CoachManmagementSystem extends javax.swing.JFrame {

    //static int usertype;
    /**
     * Creates new form CoachManmagementSystem
     */
    public CoachManmagementSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtEmaillog = new javax.swing.JTextField();
        Txtpwlog = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LoginBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        RegisterBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        COMBOusertype = new javax.swing.JComboBox<>();
        ResetBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Coach Mangement System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 627, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login Here");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 110, 640, 30));

        TxtEmaillog.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtEmaillog.setToolTipText("");
        jPanel1.add(TxtEmaillog, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 130, -1));

        Txtpwlog.setToolTipText("");
        Txtpwlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtpwlogActionPerformed(evt);
            }
        });
        Txtpwlog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtpwlogKeyTyped(evt);
            }
        });
        jPanel1.add(Txtpwlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 130, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Password*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 130, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Email Address*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 130, 20));

        LoginBTN.setBackground(new java.awt.Color(0, 0, 255));
        LoginBTN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        LoginBTN.setForeground(new java.awt.Color(255, 255, 255));
        LoginBTN.setText("Log in");
        LoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTNActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 70, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel5.setText("If you haven't  registered,");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 130, 20));

        RegisterBTN.setBackground(new java.awt.Color(153, 204, 255));
        RegisterBTN.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RegisterBTN.setForeground(new java.awt.Color(0, 0, 204));
        RegisterBTN.setText("Register now");
        RegisterBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBTNActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 100, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Password*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 130, 20));

        COMBOusertype.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        COMBOusertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~User Type~", "Customer", "Bus Employee", " " }));
        COMBOusertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMBOusertypeActionPerformed(evt);
            }
        });
        jPanel1.add(COMBOusertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 110, -1));

        ResetBTN.setBackground(new java.awt.Color(0, 0, 255));
        ResetBTN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ResetBTN.setForeground(new java.awt.Color(255, 255, 255));
        ResetBTN.setText("Reset");
        ResetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBTNActionPerformed(evt);
            }
        });
        jPanel1.add(ResetBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBTNActionPerformed

        // TODO add your handling code here:
        Register r = new Register();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegisterBTNActionPerformed

    private void TxtpwlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtpwlogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtpwlogActionPerformed

    private void TxtpwlogKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtpwlogKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_TxtpwlogKeyTyped

    private void LoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTNActionPerformed
        //Reading
        String email = TxtEmaillog.getText();
        String password = Txtpwlog.getText();
        String usertype = COMBOusertype.getSelectedItem().toString();

        //Input verification
        if (email.equals("") && password.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Email and Password are empty", "Login Error",
                    JOptionPane.ERROR_MESSAGE);

        } else if (email.equals("") && !password.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Email is Empty", "Login Error",
                    JOptionPane.ERROR_MESSAGE);

        } else if (!email.equals("") && password.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Password is Empty", "Login Error",
                    JOptionPane.ERROR_MESSAGE);

        } else if (!email.equals("") && !password.equals("")) {

            userlogin(email, password);
        }


    }//GEN-LAST:event_LoginBTNActionPerformed

    private void ResetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBTNActionPerformed
        // TODO add your handling code here:
        Resetsignup();
    }//GEN-LAST:event_ResetBTNActionPerformed

    private void COMBOusertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMBOusertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMBOusertypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoachManmagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoachManmagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoachManmagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoachManmagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoachManmagementSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> COMBOusertype;
    private javax.swing.JButton LoginBTN;
    private javax.swing.JButton RegisterBTN;
    private javax.swing.JButton ResetBTN;
    private javax.swing.JTextField TxtEmaillog;
    private javax.swing.JPasswordField Txtpwlog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void Resetsignup() {

        TxtEmaillog.setText("");
        Txtpwlog.setText("");
        COMBOusertype.setSelectedIndex(0);
        //RadioCus.setSelected(false);
        //RadioBus.setSelected(false);
    }

    private void userlogin(String email, String password) {
        //db creation
        Connection dbcon = DBConnection.CreateDBConnection();

        if (dbcon != null) {
            try {
                ResultSet rs = dbcon.createStatement().executeQuery(
                        "select * from customer where EmailAddress='" + email + "' AND Password='" + password + "' "
                );
                ResultSet Rs = dbcon.createStatement().executeQuery(
                        "select * from busemployee where EmailAddress='" + email + "' AND Password='" + password + "' "
                );

                while (rs.next() && Rs.next()) {
                    System.out.println("You are logged in");
                }
                /*while(rs.next()&& !Rs.next()){
                    System.out.println("You are logged in");
                }*/

                if (COMBOusertype.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(rootPane, "User Type is not selected", "Login Error",
                            JOptionPane.ERROR_MESSAGE);

                } else if (COMBOusertype.getSelectedIndex() == 1 && rs.first()) {

                    JOptionPane.showMessageDialog(rootPane, "loged in", "Login Success",
                            JOptionPane.INFORMATION_MESSAGE);

                    BookCoach b = new BookCoach();
                    b.setVisible(true);
                    this.setVisible(false);

                } else if (COMBOusertype.getSelectedIndex() == 2 && Rs.first()) {

                    JOptionPane.showMessageDialog(rootPane, "loged in", "Login Success",
                            JOptionPane.INFORMATION_MESSAGE);

                    AddCoach c = new AddCoach();
                    c.setVisible(true);
                    this.setVisible(false);

                } else {

                    CoachManmagementSystem login = new CoachManmagementSystem();
                    login.setVisible(true);
                    this.setVisible(false);

                    JOptionPane.showMessageDialog(rootPane, "Invalid Credentials", "Login Error",
                            JOptionPane.ERROR_MESSAGE);

                }

            } catch (SQLException ex) {
                ex.printStackTrace();

            }

        } else {
            /*JOptionPane.showMessageDialog(rootPane,"Invalid Credentials" , "Login Error", 
                            JOptionPane.ERROR);
            
            
            CoachManmagementSystem login =new CoachManmagementSystem();
            login.setVisible(true);*/

        }

    }
}

/* try {
                
                
                if(COMBOusertype.getSelectedIndex()==2){
                    BookCoach b = new BookCoach();
                    b.setVisible(true);
            
      
                }else {
                    BookCoach b = new BookCoach();
                    b.setVisible(false);
                    JOptionPane.showMessageDialog(rootPane,"User Type is not selected" , "Login Error", 
                            JOptionPane.ERROR_MESSAGE);
                }
                
                while(rs.next()){
                    System.out.println("You are logged in");
                }
                
            } catch (SQLException ex) {
                ex.printStackTrace(); 
            }*/
