/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import DbClass.DBConnection;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Prog imesh BSC
 */
public class Customer_Signup extends javax.swing.JFrame {

    static int gender;

    /**
     * Creates new form Customer_Login
     */
    public Customer_Signup() {
        initComponents();

        hidealable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtCustomerPw2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtCustomerPw = new javax.swing.JPasswordField();
        TxtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Back1BTN = new javax.swing.JButton();
        Signup1BTN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtSurename = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtTPnum = new javax.swing.JFormattedTextField();
        TxtEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtFirstname = new javax.swing.JTextField();
        RadioFemale = new javax.swing.JRadioButton();
        RadioOther = new javax.swing.JRadioButton();
        RadioMale = new javax.swing.JRadioButton();
        CResetBTN = new javax.swing.JButton();
        lblWeak = new javax.swing.JLabel();
        lblMedium = new javax.swing.JLabel();
        lblStrong = new javax.swing.JLabel();
        lblTooShort = new javax.swing.JLabel();
        lblRetype = new javax.swing.JLabel();
        lblConfirmed = new javax.swing.JLabel();
        lblWrong = new javax.swing.JLabel();
        TxtDOB = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(627, 436));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(637, 436));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Customer Register Here");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 640, 40));

        TxtCustomerPw2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtCustomerPw2.setToolTipText("");
        TxtCustomerPw2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCustomerPw2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCustomerPw2KeyTyped(evt);
            }
        });
        jPanel1.add(TxtCustomerPw2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 140, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Confirm Password*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 140, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 140, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Password*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 140, 20));

        TxtCustomerPw.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtCustomerPw.setToolTipText("");
        TxtCustomerPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCustomerPwActionPerformed(evt);
            }
        });
        TxtCustomerPw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCustomerPwKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCustomerPwKeyTyped(evt);
            }
        });
        jPanel1.add(TxtCustomerPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 140, 20));

        TxtAddress.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtAddress.setToolTipText("");
        TxtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtAddressKeyTyped(evt);
            }
        });
        jPanel1.add(TxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 140, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Email Address*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 140, 20));

        Back1BTN.setBackground(new java.awt.Color(0, 0, 255));
        Back1BTN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Back1BTN.setForeground(new java.awt.Color(255, 255, 255));
        Back1BTN.setText("Back");
        Back1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1BTNActionPerformed(evt);
            }
        });
        jPanel1.add(Back1BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 70, -1));

        Signup1BTN.setBackground(new java.awt.Color(0, 0, 255));
        Signup1BTN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Signup1BTN.setForeground(new java.awt.Color(255, 255, 255));
        Signup1BTN.setText("Signup");
        Signup1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signup1BTNActionPerformed(evt);
            }
        });
        jPanel1.add(Signup1BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("First Name*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 140, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Surename*");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 140, 20));

        TxtSurename.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtSurename.setToolTipText("");
        TxtSurename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtSurenameKeyTyped(evt);
            }
        });
        jPanel1.add(TxtSurename, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 140, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Address");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 140, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Telephone*");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 140, 20));

        try {
            TxtTPnum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtTPnum.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(TxtTPnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 140, -1));

        TxtEmail.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtEmail.setToolTipText("");
        TxtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtEmailKeyTyped(evt);
            }
        });
        jPanel1.add(TxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 140, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Date of Birth*");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 140, 20));

        TxtFirstname.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        TxtFirstname.setToolTipText("");
        TxtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFirstnameActionPerformed(evt);
            }
        });
        TxtFirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtFirstnameKeyTyped(evt);
            }
        });
        jPanel1.add(TxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 140, -1));

        buttonGroup1.add(RadioFemale);
        RadioFemale.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RadioFemale.setText("Female");
        RadioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioFemaleActionPerformed(evt);
            }
        });
        jPanel1.add(RadioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 60, -1));

        buttonGroup1.add(RadioOther);
        RadioOther.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RadioOther.setText("Other");
        RadioOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioOtherActionPerformed(evt);
            }
        });
        jPanel1.add(RadioOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, -1, -1));

        buttonGroup1.add(RadioMale);
        RadioMale.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RadioMale.setText("Male");
        jPanel1.add(RadioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 50, -1));

        CResetBTN.setBackground(new java.awt.Color(0, 0, 255));
        CResetBTN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CResetBTN.setForeground(new java.awt.Color(255, 255, 255));
        CResetBTN.setText("Reset");
        CResetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CResetBTNActionPerformed(evt);
            }
        });
        jPanel1.add(CResetBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 70, -1));

        lblWeak.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblWeak.setForeground(new java.awt.Color(204, 0, 0));
        lblWeak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWeak.setText("Weak");
        jPanel1.add(lblWeak, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 50, 20));

        lblMedium.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblMedium.setForeground(new java.awt.Color(0, 51, 204));
        lblMedium.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedium.setText("Medium");
        jPanel1.add(lblMedium, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 50, 20));

        lblStrong.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblStrong.setForeground(new java.awt.Color(51, 204, 0));
        lblStrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStrong.setText("Strong");
        jPanel1.add(lblStrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 50, 20));

        lblTooShort.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblTooShort.setForeground(new java.awt.Color(255, 102, 51));
        lblTooShort.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTooShort.setText("Too short");
        jPanel1.add(lblTooShort, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 50, 20));

        lblRetype.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblRetype.setForeground(new java.awt.Color(0, 102, 102));
        lblRetype.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRetype.setText("Re- type your password");
        jPanel1.add(lblRetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 110, 20));

        lblConfirmed.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblConfirmed.setForeground(new java.awt.Color(0, 204, 0));
        lblConfirmed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirmed.setText("Password Confirmed");
        jPanel1.add(lblConfirmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 100, 20));

        lblWrong.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblWrong.setForeground(new java.awt.Color(255, 0, 0));
        lblWrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWrong.setText("Wrong Password");
        jPanel1.add(lblWrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 90, 20));
        jPanel1.add(TxtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Back1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1BTNActionPerformed
        // TODO add your handling code here:
        Register r=new Register();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Back1BTNActionPerformed

    private void Signup1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup1BTNActionPerformed
        // read input values
        String firstname = TxtFirstname.getText();
        String surename = TxtSurename.getText();
        String email = TxtEmail.getText();
        String password = TxtCustomerPw.getText();
        String conpassword = TxtCustomerPw2.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String DOB = dateFormat.format(TxtDOB.getDate());
        
        
        String telephone = TxtTPnum.getText();
        String address = TxtAddress.getText();

        if (RadioMale.isSelected()) {
            gender = 0;
        } else if (RadioFemale.isSelected()) {
            gender = 1;
        } else if (RadioOther.isSelected()) {
            gender = 2;
        }

        //checking pw match
        if (password.equals(conpassword)) {
            
            
          savecus(firstname, surename, email, password, DOB, telephone, address, gender);
            //savecus(firstname, surename, email, password, DOB, telephone, address, gender);

        } else {
            JOptionPane.showMessageDialog(rootPane, "Passwords do not match", "Save Error",
                    JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_Signup1BTNActionPerformed

    private void RadioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioFemaleActionPerformed

    private void RadioOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioOtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioOtherActionPerformed

    private void CResetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CResetBTNActionPerformed
        // TODO add your handling code here:
        ResetCsignup();
    }//GEN-LAST:event_CResetBTNActionPerformed

    private void TxtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFirstnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtFirstnameActionPerformed

    private void TxtCustomerPwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCustomerPwKeyReleased
        // TODO add your handling code here:
        int Cpasslength = TxtCustomerPw.getText().length();

        if (Cpasslength <= 3) {
            lblTooShort.setVisible(true);
            lblWeak.setVisible(false);
            lblMedium.setVisible(false);
            lblStrong.setVisible(false);

        } else if (Cpasslength >= 4 && Cpasslength <= 6) {
            lblTooShort.setVisible(false);
            lblWeak.setVisible(true);
            lblMedium.setVisible(false);
            lblStrong.setVisible(false);

        } else if (Cpasslength >= 7 && Cpasslength <= 8) {
            lblTooShort.setVisible(false);
            lblWeak.setVisible(false);
            lblMedium.setVisible(true);
            lblStrong.setVisible(false);

        } else if (Cpasslength >= 9 && Cpasslength <= 12) {
            lblTooShort.setVisible(false);
            lblWeak.setVisible(false);
            lblMedium.setVisible(false);
            lblStrong.setVisible(true);

        }


    }//GEN-LAST:event_TxtCustomerPwKeyReleased

    private void TxtCustomerPw2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCustomerPw2KeyReleased
        // TODO add your handling code here:
        int Cpasslength2 = TxtCustomerPw2.getText().length();

        if (TxtCustomerPw.getText().equals(TxtCustomerPw2.getText())) {

            lblRetype.setVisible(false);
            lblWrong.setVisible(false);
            lblConfirmed.setVisible(true);
        } else {
            lblRetype.setVisible(false);
            lblWrong.setVisible(true);
            lblConfirmed.setVisible(false);
        }

        if (Cpasslength2 == 0) {
            lblRetype.setVisible(true);
            lblWrong.setVisible(false);

        } else if (Cpasslength2 > 0) {
            lblRetype.setVisible(false);
        }


    }//GEN-LAST:event_TxtCustomerPw2KeyReleased

    private void TxtCustomerPwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCustomerPwKeyTyped
        // TODO add your handling code here:
        int Cpasslength = TxtCustomerPw.getText().length();

        if (Cpasslength >= 12) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TxtCustomerPwKeyTyped

    private void TxtCustomerPw2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCustomerPw2KeyTyped
        // TODO add your handling code here:
        int Cpasslength = TxtCustomerPw2.getText().length();

        if (Cpasslength >= 12) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TxtCustomerPw2KeyTyped

    private void TxtCustomerPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCustomerPwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCustomerPwActionPerformed

    private void TxtFirstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFirstnameKeyTyped
        // TODO add your handling code here:
        int Cfnlen = TxtFirstname.getText().length();

        if (Cfnlen >= 15) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
            
    }//GEN-LAST:event_TxtFirstnameKeyTyped

    private void TxtSurenameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSurenameKeyTyped
        // TODO add your handling code here:
        int Csnlen = TxtSurename.getText().length();

        if (Csnlen >= 20) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TxtSurenameKeyTyped

    private void TxtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEmailKeyTyped
        // TODO add your handling code here:
         int Cemail = TxtEmail.getText().length();

        if (Cemail >= 50) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TxtEmailKeyTyped

    private void TxtAddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAddressKeyTyped
        // TODO add your handling code here:
        int Caddress = TxtAddress.getText().length();

        if (Caddress >= 100) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_TxtAddressKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back1BTN;
    private javax.swing.JButton CResetBTN;
    private javax.swing.JRadioButton RadioFemale;
    private javax.swing.JRadioButton RadioMale;
    private javax.swing.JRadioButton RadioOther;
    private javax.swing.JButton Signup1BTN;
    private javax.swing.JTextField TxtAddress;
    private javax.swing.JPasswordField TxtCustomerPw;
    private javax.swing.JPasswordField TxtCustomerPw2;
    private com.toedter.calendar.JDateChooser TxtDOB;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtFirstname;
    private javax.swing.JTextField TxtSurename;
    private javax.swing.JFormattedTextField TxtTPnum;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirmed;
    private javax.swing.JLabel lblMedium;
    private javax.swing.JLabel lblRetype;
    private javax.swing.JLabel lblStrong;
    private javax.swing.JLabel lblTooShort;
    private javax.swing.JLabel lblWeak;
    private javax.swing.JLabel lblWrong;
    // End of variables declaration//GEN-END:variables

    private void hidealable() {

        lblTooShort.setVisible(false);
        lblWeak.setVisible(false);
        lblMedium.setVisible(false);
        lblStrong.setVisible(false);
        lblRetype.setVisible(false);
        lblWrong.setVisible(false);
        lblConfirmed.setVisible(false);

    }

    private void ResetCsignup() {

        TxtFirstname.setText("");
        TxtSurename.setText("");
        TxtEmail.setText("");
        TxtCustomerPw.setText("");
        TxtCustomerPw2.setText("");
        TxtDOB.setDate(null);
        RadioMale.setSelected(false);
        RadioFemale.setSelected(false);
        RadioOther.setSelected(false);
        TxtTPnum.setText("");
        TxtAddress.setText("");

        lblTooShort.setVisible(false);
        lblWeak.setVisible(false);
        lblMedium.setVisible(false);
        lblStrong.setVisible(false);
        lblRetype.setVisible(false);
        lblWrong.setVisible(false);
        lblConfirmed.setVisible(false);

    }

    private void savecus(String firstname, String surename, String email, String password, String DOB, String telephone, String address, int gender) {

        //Connection dbcon = DBConnection.CreateDBConnection();
        //(String firstname, String surename, String email, String password, Date DOB, String telephone, String address, int gender)
        Connection dbcon;
        dbcon = DBConnection.CreateDBConnection();
        //query
        if (dbcon != null) {

            try {
                int addedcount = dbcon.createStatement().executeUpdate("insert into customer(FirstName, LastName, EmailAddress, Password, DOB, Gender, Telephone, Address)values('"+firstname+"', '"+surename+"', '"+email+"', '"+password+"', '"+DOB+"', '"+gender+"', '"+telephone+"', '"+address+"')");
                
                // + "values('" + firstname + "', '" + surename + "', '" + email + "', '" + password + "', '" + gender + "', '" + telephone + "', '" + address + "')");

                if (addedcount > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Customer successfully registered", "Save Success",
                            JOptionPane.INFORMATION_MESSAGE);
                     
                    CoachManmagementSystem signup = new CoachManmagementSystem();
                     signup.setVisible(true);
                     this.setVisible(false);
                     
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Customer registration failed", "Save Error",
                            JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Customer registration failed", "Save Error",
                        JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Customer registration failed", "Save Error",
                    JOptionPane.ERROR_MESSAGE);

        }

    }
}
