/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

/**
 *
 * @author Prog imesh BSC
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BusEmployeeBTN = new javax.swing.JButton();
        CustomerBTN = new javax.swing.JButton();
        Back1BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(627, 436));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Coach Mangement System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 650, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register As");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 650, 40));

        BusEmployeeBTN.setBackground(new java.awt.Color(102, 102, 255));
        BusEmployeeBTN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BusEmployeeBTN.setText("Bus Employee");
        BusEmployeeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusEmployeeBTNActionPerformed(evt);
            }
        });
        jPanel1.add(BusEmployeeBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 220, 60));

        CustomerBTN.setBackground(new java.awt.Color(102, 102, 255));
        CustomerBTN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CustomerBTN.setText("Customer");
        CustomerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerBTNActionPerformed(evt);
            }
        });
        jPanel1.add(CustomerBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 220, 60));

        Back1BTN.setBackground(new java.awt.Color(0, 0, 255));
        Back1BTN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Back1BTN.setForeground(new java.awt.Color(255, 255, 255));
        Back1BTN.setText("Back Home");
        Back1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back1BTNActionPerformed(evt);
            }
        });
        jPanel1.add(Back1BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 435));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BusEmployeeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusEmployeeBTNActionPerformed
        // TODO add your handling code here:
        Bus_Employees_signup bs = new Bus_Employees_signup();
        bs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BusEmployeeBTNActionPerformed

    private void CustomerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerBTNActionPerformed
        // TODO add your handling code here:
        Customer_Signup cs = new Customer_Signup();
        cs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CustomerBTNActionPerformed

    private void Back1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back1BTNActionPerformed
        // TODO add your handling code here:
        CoachManmagementSystem clog=new CoachManmagementSystem();
        clog.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_Back1BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back1BTN;
    private javax.swing.JButton BusEmployeeBTN;
    private javax.swing.JButton CustomerBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
